version: '3'

services:
  ghosthost-bot:
    image: 245045109982.dkr.ecr.eu-west-2.amazonaws.com/ghosthost:latest
    volumes:
      - ghdata:/opt/PhantomBot_data
    environment:
      PHANTOMBOT_ENVOVERRIDE: 'true'
      PHANTOMBOT_USEHTTPS: 'false'
      PHANTOMBOT_PROXYBYPASSHTTPS: 'true'
      PHANTOMBOT_USER: ${BOT_NAME}
      PHANTOMBOT_CHANNEL: ${USER_NAME}
      PHANTOMBOT_PANELUSER: ${PANEL_USER_NAME}
      PHANTOMBOT_PANELPASSWORD: ${PANEL_PASSWORD}
      PHANTOMBOT_DISCORD_TOKEN: ${DISCORD_TOKEN}
      PHANTOMBOT_RESTARTCMD: ${RESTART_CMD}
      PHANTOMBOT_TILTIFY_TOKEN: ${TILTIFY_TOKEN}
      PHANTOMBOT_TWITTER_ACCESS_TOKEN: ${TWITTER_ACCESS_TOKEN}
      PHANTOMBOT_TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
      PHANTOMBOT_TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET}
      PHANTOMBOT_TWITTER_SECRET_TOKEN: ${TWITTER_SECRET_TOKEN}
      PHANTOMBOT_TWITTERUSER: ${TWITTER_USER}
      PHANTOMBOT_YOUTUBEKEY: ${YOUTUBE_KEY}
    networks:
      - traefik-public
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 5
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 200M
      placement:
        constraints:
          - "node.role!=manager"
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.http.routers.gh-${USER_NAME}-http.entrypoints=http
        - traefik.http.routers.gh-${USER_NAME}-http.middlewares=https-redirect
        - traefik.http.routers.gh-${USER_NAME}-http.rule=Host(`${HOST_NAME}`)
        - traefik.http.routers.gh-${USER_NAME}-https.entrypoints=https
        - traefik.http.routers.gh-${USER_NAME}-https.rule=Host(`${HOST_NAME}`)
        - traefik.http.routers.gh-${USER_NAME}-https.tls=true
        - traefik.http.routers.gh-${USER_NAME}-https.tls.certresolver=le
        - traefik.http.services.gh-${USER_NAME}.loadbalancer.server.port=25000

networks:
  traefik-public:
    external: true

volumes:
  ghdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/efs/clients/${USER_NAME}
