version: '3'

services:
  ghosthost-bot:
    image: 245045109982.dkr.ecr.eu-west-2.amazonaws.com/ghosthost:latest
    volumes:
      - /mnt/efs/clients/${USERNAME}:/opt/PhantomBot_data
    environment:
      PHANTOMBOT_USER: ${BOT_NAME}
      PHANTOMBOT_OAUTH: ${BOT_OAUTH}
      PHANTOMBOT_CHANNEL: ${USER_NAME}
      PHANTOMBOT_APIOAUTH: ${USER_OAUTH}
      PHANTOMBOT_PANELUSER: ${PANEL_USER_NAME}
      PHANTOMBOT_PANELPASSWORD: ${PANEL_PASSWORD}
      PHANTOMBOT_USEHTTPS: "false"
      PHANTOMBOT_DISCORD_TOKEN: ${DISCORD_TOKEN}
      PHANTOMBOT_RESTARTCMD: ${RESTART_CMD}
      PHANTOMBOT_TILTIFY_TOKEN: ${TILTIFY_TOKEN}
      PHANTOMBOT_TWITTER_ACCESS_TOKEN: ${TWITTER_ACCESS_TOKEN}
      PHANTOMBOT_TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
      PHANTOMBOT_TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET}
      PHANTOMBOT_TWITTER_SECRET_TOKEN: ${TWITTER_SECRET_TOKEN}
      PHANTOMBOT_TWITTERUSER: ${TWITTER_USER}
      PHANTOMBOT_YOUTUBEKEY: ${YOUTUBE_KEY}
    networks:
      - traefik-public
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 100M
      labels:
      - traefik.http.services.gh-${USER_NAME}.loadbalancer.server.port=25000
      - traefik.http.routers.gh-${USER_NAME}.rule=Host(`${HOST_NAME}`)
      - traefik.http.routers.gh-${USER_NAME}.entrypoints=http
      - traefik.http.routers.gh-${USER_NAME}.entrypoints=https
      - traefik.http.routers.gh-${USER_NAME}.tls=true
      - traefik.http.routers.gh-${USER_NAME}.tls.certresolver=le
      - traefik.http.middlewares.gh-${USER_NAME}.redirectscheme.scheme=https
      - traefik.http.middlewares.gh-${USER_NAME}.redirectscheme.permanent=true
